name: Connect VPN

on:
  workflow_call:
    inputs:
      mi_variable:
        type: string
        required: true
        description: "Variable to be passed to the job"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo "Conectando ${{ inputs.mi_variable }}"
