name: Generate pre release
on:
  workflow_call:
    inputs:
      status:
        type: string
        description: Matrix status
      job_name:
        type: string
    outputs:
      matrix_status:
        description: "List of matrix status"
        value: ${{ jobs.getMatrixStatus.outputs.matrix_status }}
jobs:
  getMatrixStatus:
    runs-on: ubuntu-latest
    outputs:
      matrix_status: ${{ steps.get_matrix_status.outputs.matrix_status }}
    steps:
      - name: Get matrix status
        id: get_matrix_status
        run: |
          list_matrix_status=""
          page=1       
          num_jobs=1

          while [ num_jobs -gt 0 ]; do
            jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs?per_page=100&page=$page)
            num_jobs=$(echo "$jobs" | jq '.jobs | length')         
            matrix_status=$(echo "$jobs" | jq -r '.jobs | map(select(.conclusion == "${{ inputs.status}}" and (.name | tostring | startswith("${{ inputs.job_name}}")))) | map(.name) | join("|")')
            echo list_matrix_status="$list_matrix_status $matrix_status"
            page=$((page + 1 ))
            
          done

          echo $list_matrix_status
          echo "matrix_status=$list_matrix_status" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
