# This is a basic workflow to help you get started with Actions

name: Print

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      saludo:
        type: string
      mensaje:
        type: string
        required: false
        default: "QUE HAY"

env:
  NOMBRE_ENV: 'MY_INPUT_${{ inputs.saludo }}'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mi_saludo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: print env
        run: echo '${{ env.NOMBRE_ENV}}'
      - name: if var
        run: |
          echo "valor de var ${{ vars['REPO_VALOR_QA'] }}"
          echo "segundo var  ${{ vars.REPO_VALOR_QA }}"
          if [ vars["REPO_VALOR_QA"] = '5' ]; then
            echo "valor es cinco"
          else
            echo "que paso  ${{ vars['REPO_VALOR_QA'] }}"
          fi
      - name: Print Readme
        run: |
          cat README.md
      - name: Print mensaje
        run: echo "${{ inputs.mensaje }}"

      # Runs a single command using the runners shell
      - name: Get repository
        run: |
          echo "ONLY_REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
      - name: Print repo
        run:
          echo "name repo - ${{ env.ONLY_REPO_NAME }}"
      - name: Run a one-line script
        run: |          
          echo "Mi repository ${{ github.repository }}"
