# This is a basic workflow to help you get started with Actions

name: Print

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      saludo:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mi_saludo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Get repository
        run: |
          echo "ONLY_REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
      - name: Print repo
        run:
          echo "name repo - ${{ env.ONLY_REPO_NAME }}"
      - name: Run a one-line script
        run: |          
          echo "Mi repository ${{ github.repository }}"
